config/routes.rb
Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :users
  resources :sessions

  root :to => 'questions#index'
  resources :questions do
    resources :answers
  end
  resources :blogs
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  validates :description, :presence => true

  belongs_to :user
  belongs_to :question
end

app/models/blog.rb
class Blog

  attr_reader :title, :body, :type, :images, :caption, :video, :answer

  def initialize(params)
    @title = params["title"]
    @body = params["body"]
    @type = params["type"]
    @images = params["photos"] if params["photos"]
    @caption = params["caption"]
    # @answer = answer_params
    # binding.pry
    # @video = params["player"].first['embed_code'] if params["player"]
  end

  def self.all
    blogs = []
    client = Tumblr::Client.new
    response = client.posts("houseofsoundradio.tumblr.com")
    response["posts"].each do |blog_attributes|
      blogs << Blog.new(blog_attributes)
    end
    blogs
  end

  private

  # def answer_params
  #   params.require(:answer).permit(:question)
  # end
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :description, :presence => true
  validates :topic, :presence => true

  belongs_to :user
  has_many :answers
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :user_name, :presence => :true
  has_secure_password
  validates_uniqueness_of :user_name

  has_many :questions
  has_many :answers
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_filter :authorize, only: [:new, :create, :destroy, :edit, :update]


  def index
    @answers = Answers.all
    @users = User.all
  end

  def new
    @answer = Answer.new
    @question = Question.find_by_id(params[:question_id])
  end

  def create
    @question = Question.find_by_id(params[:question_id])
    @answer = Answer.create(answer_params)
    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
  end

  def destroy
    @answer = Answer.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to question_path(@question) }
      format.js
    end
  end


  private

  def answer_params
    params.require(:answer).permit(:description).merge(question_id: @question.id, user_id: current_user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

  def authorize
    redirect_to login_url, alert: "Not Authorized" if current_user.nil?
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController

before_filter :authorize, except: [:index, :show]

  def index
    @blogs = Blog.all
  end

  def show
    @blogs = Blog.all
    @blog = Blog.find(params[:id])
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_filter :authorize, only: [:edit, :update, :new, :create, :destroy]

  def index
    @questions = Question.all
    @users = User.all
    if params[:search].blank? == false
      @questions = Question.basic_search(params[:search])
    end
    respond_to do |format|
      format.html
      format.js
    end
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.create(question_params)
    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    # else
    #   render 'create', alert: "Please enter a valid question."
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers.all
    @answer = Answer.new
  end

  def destroy
    @question = Question.destroy(params[:id])
    respond_to do |format|
      format.html { redirect_to root_url }
      format.js
    end
  end

  private

  def question_params
    params.require(:question).permit(:description, :topic).merge(user_id: current_user.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_user_name(params[:user_name])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_url, notice: "Logged in!"
    else
      flash.now.alert = "Email or password is invalid."
    end
  end

  def destroy
    session[:user_id] = nil
    respond_to do |format|
      format.html { redirect_to root_url, notice: "Logged out!" }
      format.js
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_url, notice: "Thank you for signing up!"
    else
      render "new"
    end
  end

  private

  def user_params
    params.require(:user).permit(:user_name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/answers/_answer.html.erb
<blockquote id="answer_<%= answer.id %>">
  <font size="2"><%= "#{answer.description}" %></font>
  <footer> answered by <strong><%= "#{answer.user.user_name}" %></strong> @ <%= "#{answer.created_at.localtime.strftime("%d %b. %Y, %I:%M%p")}" %></footer>
  <font size="1"><%= link_to "(remove)", question_answer_path(@question, answer), method: :delete, data: {confirm: "Are you sure?"}, id: "remove_a", remote: true %></font>
</blockquote>

app/views/answers/_form.html.erb
<%= form_for [@question, @answer], remote: true do |f| %>
  <%= f.label :description %>
  <textarea class="form-control" rows="3" id="answer_description" name="answer[description]" type="text"></textarea>
  <%= f.submit(:class => "btn btn-primary") %>
<% end %>

app/views/answers/create.js.erb
$('#new_answer').remove();
$('#notice').empty();
$('#notice').show().append('<%= j "Your answer has been added!" %>');
$('#description').show();
$('#answers').show().prepend('<%= j render(@answer) %>');
$('#reply_to_q').show();

app/views/answers/destroy.js.erb
$('#answer_<%= @answer.id %>').remove();
$('#answers').show()

app/views/answers/new.js.erb
$(function () {
  $('#reply_to_q').hide().after('<%= j render("form") %>');
});

app/views/blogs/index.html.haml
%div.col-xs-12.post-index-head
  = link_to "Index page", questions_path, class: "btn btn-warning"

%div.col-xs-12.col-sm-5.border-all-posts
  %h3 Recent Tumblr Blog Posts
  - @blogs.each do |blog|
    %pre
      %div.each-post
        %div.each-title
          = blog.title.to_s.html_safe
        %div.each-body
          = blog.body.to_s.html_safe
        %div
          - if blog.images
            - blog.images.each do |image|
              = image_tag(image["original_size"]["url"], class: "img img-responsive")
        %div
          - if blog.video
            = video_tag("#{blog.video.html_safe}", class: "img img-responsive")
        %div.each-caption
          = blog.caption.to_s.html_safe
        / %div.each-question
        /   = blog.question.to_s.html_safe
        %div.each-answer
          = blog.answer.to_s.html_safe

        / %div
        /     = video_tag(video[][], class: "img img-responsive")

app/views/layouts/application.html.haml
!!!
%html
%head
  = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
  = javascript_include_tag 'application', 'data-turbolinks-track' => true
  = csrf_meta_tags

%body
  .container
    #user_header.text-right
      - if current_user
        Logged in as #{current_user.user_name}.
        %br/
        = link_to "Log Out", logout_path
      - else
        = link_to "Sign Up", signup_path
        or
        = link_to "Log In", login_path

    %h1.text-center
      = link_to "Stack Underflow", questions_path
    %p#notice.bg-success= flash[:notice]
    %p#alert.bg-danger= flash[:alert]
    / div class whatever
    = yield
    / end div

app/views/questions/_form.html.haml
= form_for @question, remote: true do |f|
  = f.label :topic
  %textarea#question_topic.form-control{rows:"1", name:"question[topic]", type:"text"}
  = f.label :description
  %textarea#question_description.form-control{rows:"3", name:"question[description]", type:"text"}
  = f.submit(:class => "btn btn-primary")

app/views/questions/_question.html.haml
%p.list-group-item{id: "question_#{question.id}", remote: true}
  #{link_to question.topic, question_path(question)} by
  = question.user.user_name
  at
  = "#{question.created_at.localtime.strftime("%d %b. %Y, %I:%M%p")}"
  = link_to "(remove)", question, method: :delete, data: {confirm: "Are you sure?"}, id: "remove_q", remote: true

app/views/questions/create.js.erb
$('#new_question').remove();
$('#notice').empty();
$('#notice').show().append('<%= j "Your question has been added!" %>');
$('#questions').show().prepend('<%= j render(@question) %>');
$('#add_q').show();

app/views/questions/destroy.js.erb
$('#question_<%= @question.id %>').remove();

app/views/questions/index.html.haml
.list-group
  - if current_user
    = link_to "Add a New Question", new_question_path, :class => "btn btn-success btn-lg", id: "add_q", remote: true

= form_tag questions_path, method: :get, remote: true do
  %p
    = text_field_tag :search, params[:search]
    = submit_tag "Search", name: nil

= link_to "Tumblr Blogs", blogs_path, class: "btn btn-warning"

%h4 Topic of Discussion:
#questions.list-group
  - @questions.reverse_each do |question|
    %p.list-group-item{:id => "question_#{question.id}"}
      #{link_to question.topic, question_path(question)} by
      = question.user.user_name
      at
      = "#{question.created_at.localtime.strftime("%d %b. %Y, %I:%M%p")}"
      = link_to "(remove)", question, method: :delete, data: {confirm: "Are you sure?"}, id: "remove_q", remote: true

app/views/questions/index.js.erb
// $('#description').hide();
// $('#answers').hide();
$('#questions').empty();
$('#questions').prepend('<%= j render(@questions) %>');

app/views/questions/new.js.erb
$('#add_q').hide().after('<%= j render("form") %>');

app/views/questions/show.html.haml
%pre
  %p#description
    %strong
      Topic: #{@question.topic}
      / %br
      Question:
    #{@question.description}
    %br/
    BY #{@question.user.user_name} @ #{@question.created_at.localtime.strftime("%d %b. %Y, %I:%M%p")}

.list-group
  - if current_user
    = link_to "Reply", new_question_answer_path(@question), :class => "btn btn-success btn-lg", id: "reply_to_q", remote: true

#answers
  - @question.answers.reverse_each do |answer|
    %blockquote{id:"answer_#{answer.id}"}
      %font{size:"2"}
        = "#{answer.description}"
      %footer
        answered by
        %strong
          = "#{answer.user.user_name}"
        @ #{"#{answer.created_at.localtime.strftime("%d %b. %Y, %I:%M%p")}"}
      %font{size:"1"}
        = link_to "(remove)", question_answer_path(@question, answer), method: :delete, data: {confirm: "Are you sure?"}, id: "remove_a", remote: true

%br/

app/views/users/new.html.haml
%h1 Sign Up
= form_for @user do |f|
  - if @user.errors.any?
    .error_messages
      %h2 Form is invalid
      %ul
        - @user.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :user_name
    %br/
    = f.text_field :user_name
  .field
    = f.label :password
    %br/
    = f.password_field :password
  .field
    = f.label :password_confirmation
    %br/
    = f.password_field :password_confirmation
  %br/

  .actions= f.submit "Sign up"